parent=keycloak
import=common/keycloak

styles=web_modules/@patternfly/react-styles/css/components/Button/button.css \
  web_modules/@patternfly/react-styles/css/components/Form/form.css \
  web_modules/@patternfly/react-styles/css/components/FormControl/form-control.css \
  web_modules/@patternfly/react-styles/css/components/ActionList/action-list.css \
  node_modules/@patternfly/patternfly/patternfly-base.css \
  node_modules/@patternfly/patternfly/components/Button/button.css \
  node_modules/@patternfly/patternfly/components/Form/form.css \
  node_modules/@patternfly/patternfly/components/FormControl/form-control.css \
  node_modules/@patternfly/patternfly/components/Login/login.css \
  node_modules/@patternfly/patternfly/components/Alert/alert.css \
  node_modules/@patternfly/patternfly/components/InputGroup/input-group.css \
  css/login.css
