spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/userprofiles}
      database: userprofiles
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8083}/realms/${KEYCLOAK_REALM:medbridge}/protocol/openid-connect/certs

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
